lib/zeitwerk/inflector.rb

We can allocate a little bit less objects and gain 10%+ speedup ;) 
```ruby
Basename: api
ips benchmark:
Warming up --------------------------------------
original    84.379k i/100ms
patch    82.549k i/100ms
Calculating -------------------------------------
original      1.142M (± 8.1%) i/s -      5.653M in   5.002194s
patch      1.251M (± 3.6%) i/s -      6.274M in   5.022751s
Comparison:
patch:  1250819.4 i/s
original:  1141609.0 i/s - same-ish: difference falls within error
memory benchmark:
Calculating -------------------------------------
original   368.000  memsize (     0.000  retained)
6.000  objects (     0.000  retained)
2.000  strings (     0.000  retained)
patch   288.000  memsize (     0.000  retained)
4.000  objects (     0.000  retained)
1.000  strings (     0.000 …
```

Mutate array and strings

---

lib/zeitwerk/loader.rb

`{}.each_key.reject` creates 2 arrays.
`{}.keys.delete_if` creates 1 array.
1 item in `dirs` and 0 items in `ignored`:
```ruby
ips benchmark:
Warming up --------------------------------------
original    91.571k i/100ms
patch   201.972k i/100ms
Calculating -------------------------------------
original      1.614M (± 7.0%) i/s -      8.058M in   5.018787s
patch      4.342M (± 2.2%) i/s -     21.813M in   5.026412s
Comparison:
patch:  4341870.6 i/s
original:  1613954.0 i/s - 2.69x  slower
memory benchmark:
Calculating -------------------------------------
original   168.000  memsize (     0.000  retained)
2.000  objects (     0.000  retained)
0.000  strings (     0.000  retained)
patch    40.000  memsize (     0.000  retained)
1.000  objects (     0.000  retained)
0.000  strings ( …
```

Improve speed and memory usage of Zeitwerk::Loader#actual_dirs

---

lib/zeitwerk/loader.rb

The logic for pre-loading a single path was spread in several methods. This patch tries to unify them into a single method that can be reused.
Feel free to ignore it if everything was done that way on purpose, I wasn't really sure if it made sense to factor this logic out.
PS. Your work on this loader is amazing, it makes it really easy to grasp such a core concept in Ruby.

Add Loader#do_preload_abspath to process single absolute paths

---

lib/zeitwerk/loader.rb
test/lib/zeitwerk/test_explicit_namespace.rb

Ok, so I stepped upon a weird corner case which is summed up in the included test case (that fails on master).
Took me a while to figure out, I tried reproducing the behavior in small snippets without success, until I noticed it's a behavior that is specific to classes and I was trying to repro with modules.
Small snippet to showcase that behavior:
```ruby
class Foo
autoload :Eggspam, 'eggspam.rb'
end
class Bar < Foo
end
p Foo.autoload?(:Eggspam) # => 'eggspam.rb'
p Bar.autoload?(:Eggspam) # => 'eggspam.rb'
```
TL;DR; `autoload` directives are inherited from parent classes.
Because of this, having both `Bar` and `Foo::Bar` only works if `Foo` is a module and not a class, unless `Bar` is reference before `Foo::Bar`.
`autoload_for?` is being used to not register a new autoload if one is …

Handle a similar name being used both inside a class and it's parent

---

lib/zeitwerk/loader.rb
test/lib/zeitwerk/test_eager_load.rb

As discussed in https://github.com/fxn/zeitwerk/pull/20#issuecomment-472324682 I'm trying to bring back the possibility to have directories being autoloaded, but not eager loaded.
This is more or less a revert of https://github.com/fxn/zeitwerk/commit/a1bd83b10521f41f7f74e921602839a1813d11e4
I tested it with [this Rails patch](https://github.com/rails/rails/compare/master...Shopify:zeitwerk-autoload-paths-2) and it seems to work as expected.
@fxn would you be ok with bringing that feature back?
cc @rafaelfranca @Edouard-chin

Bring back the do_not_eager_load feature

---

lib/zeitwerk/explicit_namespace.rb

While experimenting with Zeitwerk on an existing Rails app, one test became extremely slow (I'm not even sure how long it takes as it never completed, but I estimate it at over 15 minutes, from ~3s previously).
So I decided to profile that test (or rather a subset of what it's doing) and got this:
```
$ stackprof tmp/stackprof-stripe-wall-.dump 
==================================
Mode: wall(1000)
Samples: 6 (83.78% miss rate)
GC: 0 (0.00%)
==================================
TOTAL    (pct)     SAMPLES    (pct)     FRAME
5  (83.3%)           5  (83.3%)     block in <module:ExplicitNamespace>
1  (16.7%)           1  (16.7%)     Set#each
5  (83.3%)           0   (0.0%)     Stripe::StripeObject#metaclass
1  (16.7%)           0   (0.0%)     Stripe::StripeObject#remove_accessors
6 (100.0%) …
```

Optimize the TracePoint callback

---

lib/zeitwerk/explicit_namespace.rb
test/lib/zeitwerk/test_explicit_namespace.rb

Followup to: https://github.com/fxn/zeitwerk/pull/24
Turns out we can't use break here, otherwise we get a `LocalJumpError: break from proc-closure` (which makes me wonder if we could have a callback without a closure, which perf wise could be interesting, but that's another story).
The test case to exercise this code path is a bit complicated, as need extra unloaded namespaces to ensure the loader stays enabled.
This only test singleton classes, I tried to generate a case for regular anonymous classes with `Class#new` and `Module#new`, but without success so far. I don't know why TracePoint doesn't trigger in these cases.
@fxn

Add a test case for singleton classes in TracePoint, and fix next vs break

---

lib/zeitwerk/loader.rb

It uses 33% less memory when `paths` is not an array and 50% when `paths` is an array.

Improve expand_paths memory usage

---

lib/zeitwerk/loader.rb

This warning has been removed in Ruby 2.6. But now this gem supports lower version, so I think it should be fixed.

Fix "warning: shadowing outer local variable - dir"

---

lib/zeitwerk/loader.rb

If `Zeitwerk::Loader.for_gem` is called from a file which contains `:` in its path, `called_from` will be misunderstood.
We can get correct filenames via `caller_locations`.
```ruby
require 'zeitwerk'
loader = Zeitwerk::Loader.for_gem
puts loader.tag # => tm
```
I know this rarely happens in actual because bundle path and gem name cannot contain `:`. But my code seems somehow more readable.

Use caller_locations to get caller filepath

---

lib/zeitwerk/inflector.rb

Since `Zeitwerk::Inflector#camelize` is an instance method, I have fixed the document to follow the code.

Fix document on Inflector usage

---

lib/zeitwerk/explicit_namespace.rb

To be honest the main justification for this change is "cosmetic". The TracePoint is one of the main Zeitwerk hotspots, and as such often appear in profiles under the `block in <module:ExplicitNamespace>` name.
I'd prefer if it had a more descriptive name.
There's also probably some extremely marginal performance gain by getting rid of a closure in favor of a method, but it's likely so small that I don't think it's worth benchmarking.

Refactor ExplictlNamespace tracepoint to use a method rather than a block

---

lib/zeitwerk/error.rb
lib/zeitwerk/loader.rb
test/lib/zeitwerk/test_exceptions.rb

Ref: https://github.com/fxn/zeitwerk/issues/72 https://github.com/fxn/zeitwerk/issues/73
People seem to be confused by this error. However it's a totally legitimate error case, and after playing with it a bit I don't think automatically silencing those is a good idea, because if you customize the inflector and include a bug in it, you might have a hard time figuring it out.
However I think what we can do is to improve the error message, so that users better understand what happened, and can fix the issue themselves without opening an issue on GitHub.
NB: doc/writing isn't exactly my *forte*, so alternative error messages are welcome.
Also I chose to subclass `::NameError`, so that it's clearer that it's about Zeitwerk, and also to allow Rails (arguably the main way people we use Zeitwerk) …

Better error for invalid constant names

---

lib/zeitwerk/inflector.rb
test/lib/test_inflector.rb

Adds a Zeitwerk::Inflector#inflect method which can be used to explicitly define custom inflections that take priority over the default Zeitwerk::Inflector#camelize behaviour, per https://github.com/fxn/zeitwerk/pull/88#issuecomment-538712084
Using a double underscored ivar to avoid clashes with existing `@inflections` and using a private reader method to prevent `instance variable @__inflections not initialized` warnings.

Add Zeitwerk::Inflector#inflect method

---

lib/zeitwerk/loader.rb
lib/zeitwerk/real_mod_name.rb

Both were added in MRI 2.7.
The first one is `Module#autoload?` now taking a second argument
to restrict the search to the module itself.
https://bugs.ruby-lang.org/issues/15777
The second is the new `UnboundMethod#bind_call` that allows
calling an unbound method without first allocating a `Method`
instance.
https://bugs.ruby-lang.org/issues/15955
@fxn 
cc @rafaelfranca @Edouard-Chin @etiennebarrie

Enable two optimization for newer rubies

---

lib/zeitwerk/loader/callbacks.rb
test/lib/zeitwerk/test_exceptions.rb

This is related to https://github.com/rails/rails/pull/37599, in short I'm trying to remove all `require_dependency` usage in Rails, and the last one is here: https://github.com/rails/rails/blob/cb740af5c96ebe0beea01fb8c62e93fb581ad454/actionpack/lib/abstract_controller/helpers.rb#L154
What Rails is doing there is that it `require_dependency` the expected file to know wether the constant doesn't exist, or wether it's loading fails.
So rewrite that code for pure Zeitwerk usage, I need to be able to do the same differentiation, e.g. if I get a `NameError` trying to access `FooHelper`, it can be either `NameError: expected file app/helpers/foo_helper.rb to define constant FooHelper, but didn't` or `NameError: uninitialized constant FooHelper`.
If it's the former I should re-raise it, if it's …

Raise a Zeitwerk::NameError when a file does not define the expected constant

---

lib/zeitwerk/loader.rb
lib/zeitwerk/loader/callbacks.rb
test/lib/zeitwerk/test_exceptions.rb

Context: https://github.com/rails/rails/issues/37650
TL;DR; vanilla `NameError` has a `#name` accessor that is useful to distinguish wether the constant we were trying to load is missing, or if the `NameError` is caused by some dependent code.
e.g. being able to tell the difference between:
```ruby
class FoosControler # The expected constant doesn't exist
end
```
```ruby
class FooControler
::DoesNotExist # Another constant resolution issue was triggered by loading foo_controlle.rb
end
```
What this patch does is to respect the `NameError#name` contract.
@fxn for review please.
cc @rafaelfranca @etiennebarrie @Edouard-Chin

Properly set Zeitwerk::NameError#name

---

lib/zeitwerk/loader.rb

Not a huge deal at all, but I noticed a surprising amount of allocations from this idiom:
```
Allocated String Report
-----------------------------------
109381  ""
13344  ~/gems/zeitwerk-2.2.2/lib/zeitwerk/loader.rb:479
```
Turns out `slice!` allocates a wierd empty string for no reasons,
as well as a string containing the sliced chars we don't care about:
```ruby
>> s = "foo.rb"; MemoryProfiler.report { s.slice!(-3, 3) }.pretty_print
Allocated String Report
-----------------------------------
1  ""
1  (irb):20
1  ".rb"
1  (irb):20
```
Based on the context, I assume the `slice!` usage goal was to save some
string allocations, but turns out it actually makes things worse.
Two other candidate methods could be:
- `byteslice`, as it ignore encoding it's marginally faster than `slice`.
- …

Micro optimization: `slice(0...-3)` is actually faster than `slice!(-3, 3)`

---

zeitwerk.gemspec

For a nice “Changelog” link in the https://rubygems.org/gems/zeitwerk sidebar.

Add changelog to gemspec

---

lib/zeitwerk/loader.rb

Most of the `File` methods cast the paths it receives with [`FilePathValue / rb_get_path`](https://github.com/ruby/ruby/blob/09b936d89cb66e38db46dbe782aa5f22f94656bc/file.c#L244-L248) which ultimately delegate to [`rb_new_str_frozen`](https://github.com/ruby/ruby/blob/09b936d89cb66e38db46dbe782aa5f22f94656bc/file.c#L225-L236) (aliased as `rb_str_new4`).
[`rb_new_str_frozen` could be experessed as `str.frozen? ? str : str.dup`.](https://github.com/ruby/ruby/blob/09b936d89cb66e38db46dbe782aa5f22f94656bc/string.c#L1217-L1222)
So by freezing the paths passed to the various `File.` methods, we
save at least one useless allocation each time, unless the string encoding
is incompatible with the file system.
```
s = __FILE__
alloc = GC.stat[:total_allocated_objects]
File.realpath(s)
p …
```

Freeze absolute paths for reduce allocations on file operations

---

lib/zeitwerk/inflector.rb

```ruby
Basename: point_3d_value
ips benchmark:
Warming up --------------------------------------
original    46.940k i/100ms
patch    52.230k i/100ms
Calculating -------------------------------------
original    502.884k (± 4.0%) i/s -      2.535M in   5.048545s
patch    559.661k (± 4.7%) i/s -      2.820M in   5.050832s
Comparison:
patch:   559660.8 i/s
original:   502883.7 i/s - 1.11x  (± 0.00) slower
memory benchmark:
Calculating -------------------------------------
original   568.000  memsize (     0.000  retained)
11.000  objects (     0.000  retained)
6.000  strings (     0.000  retained)
patch   448.000  memsize (     0.000  retained)
8.000  objects (     0.000  retained)
4.000  strings (     0.000  retained)
Comparison:
patch:        448 allocated
original:        568 allocated …
```

Capitialize! parts of basename

---

lib/zeitwerk/loader.rb

We had an issue in our codebase where we would see a mysterious `ArgumentError - wrong number of arguments (given 2, expected 3)` that was being traced to this line:
(gem) zeitwerk-2.3.0/lib/zeitwerk/loader.rb:796:in `unload_autoload'
We finally realized that this is down to a class in our codebase that defines its own `self.send` method (that does something unrelated, hence the mismatch in arity). 
Now I'm completely aware that this is bad practice and we're going to fix the offending class, but it's also true that the resulting error message is very confusing and it's not immediately clear how to fix it.
If zeitwerk was to use `__send__` instead of `send` it would avoid this issue. I'm not sure if there are any downsides to this, or if this should be merged at all -- consider this pull …

Use __send__ instead of send

---

.travis.yml

Also, I'm wondering whether `truffleruby` has been added to "allow_failures"
category by mistake? Suppose we should add `truffleruby-head` instead.
Since tests for `truffleruby` are green for a couple of the last builds
https://github.com/fxn/zeitwerk/runs/1577391820

Add Ruby 3.0 on CI matrix

---

lib/zeitwerk/loader.rb

I was surprised to see `BasicObject.equal?` show up in my profiles
Instead we can use `==`, It's very slightly faster because MRI has a dedicated `opt_eq` opcode, and by calling in on `Object` it's just as unlikely to be overridden than `equal?`.
```ruby
require 'benchmark/ips'
parent = Object
Benchmark.ips do |x|
x.report('==') { Object == parent  }
x.report('equal?') { Object.equal?(parent)  }
x.compare!
end
```
```
Warming up --------------------------------------
==     2.299M i/100ms
equal?     1.951M i/100ms
Calculating -------------------------------------
==     22.960M (± 1.0%) i/s -    114.964M in   5.007555s
equal?     19.374M (± 1.3%) i/s -     97.551M in   5.036074s
Comparison:
==: 22960357.5 i/s
equal?: 19373931.9 i/s - 1.19x  (± 0.00) slower
```
Overall the gain is small, …

Minor performance optimizations in Loader#cperf

---

lib/zeitwerk.rb

Was just working on https://github.com/testdouble/good-migrations/issues/9 and noticed that `Zeitwerk::VERSION` is not available by default, so it seemed like something that should be loaded with the rest of the gem.
Feel free to take it or leave it!

Load zeitwerk's `VERSION` constant

---

lib/zeitwerk/loader/config.rb

This commit converts the `#tag` `attr_acessor` into an `attr_reader` to
make the library warning free. This is caused by the re-definition of
`Zeitwerk::Loader::Config#tag=` further down in the same file.
As we are defining a custom writer, we can convert the `attr_accessor`
into an `attr_reader` safely.

Convert `Zeitwerk::Loader::Config#tag` from accessor to reader

---

lib/zeitwerk/kernel.rb

Ref: https://github.com/Shopify/bootsnap/pull/389
I wondered the same, and was surprised to see it work. Turns out it was fixed recently.

Update the Kernel#require comment about prepend

---

Rakefile

This PR enables rake's test task to opt into running the test suite with
warnings, this is to avoid warnings sneaking into the library.
Illustrative example:
```
% git diff
diff --git a/lib/zeitwerk.rb b/lib/zeitwerk.rb
index a1335d1..615d516 100644
--- a/lib/zeitwerk.rb
+++ b/lib/zeitwerk.rb
@@ -16,6 +16,7 @@ module Zeitwerk
def self.with_loader
+    a = 1
loader = Zeitwerk::Loader.new
yield loader
ensure
% bundle exec rake
/Users/teo/src/github.com/fxn/zeitwerk/lib/zeitwerk.rb:19: warning: assigned but unused variable - a
... output omitted ...
```

Enable warnings when running tests

---

lib/zeitwerk/loader/helpers.rb

The yield order of `Dir.each_entry` is directly dependent from the file system implementation. On macOS they will be yielded in alphabetical order, because that's how HFS is implemented.
However on Linux, different file system expose different orders. Most commonly, files are iterated with the last modified first, which across a fleet of server is akin to "random".
This small disrependency can cause order dependent code to fail. Arguably, it's the user code that is faulty and should be fixed (I agree), but even then, a predictable order makes it easier to debug.
For that same reason, since Ruby 3 `Dir[]` is sorted: https://bugs.ruby-lang.org/issues/8709
@fxn what do you think?
cc @jeromegn

Eager load constants in a consistent order

---

lib/zeitwerk/loader/config.rb

Since b5a63c2c00e3f908d78378a5a59659702c175f23 root_dirs does not have `true` as values, but namespace module instead.

Document namespace values for Zeitwerk::Loader::Config#root_dirs

---

lib/zeitwerk/loader.rb
test/lib/zeitwerk/test_conflicting_directory.rb

The current implementation ends up clobbering the `dir` variable
after checking the first loader in `Registry.loaders`.  As a result
if you have multiple loaders, the `loader.ignores?(dir)` check
will be guaranteed to fail even if the loader actually ignores
the directory, since there is a stray `/` at the end of the path.

Fix Erroenous Conflicting Directory Error

---

test/lib/zeitwerk/test_exceptions.rb

I noticed this constant was hanging around after the test was done.

Remove `TyPo` constant in teardown

---

Gemfile
test/test_helper.rb

This PR adds minitest-proveit to force that all tests executes some kind
of assertion, and if they do not - they will fail automatically.

Add minitest-proveit to force assertions

---

lib/zeitwerk/loader.rb

It appears that `EOS` is not defined nor not reachable.

Remove unrechable code

---

README.md

Hello!
I noticed I was running into the issue with byebug and zeitwerk mentioned in the README and in [this byebug issue](https://github.com/deivid-rodriguez/byebug/issues/564). I tried switching to debug.rb but had the same issue, which confused me since the docs mention it's compatible. As far as I can tell from the various GH issues, the debug.rb incompatibility was fixed in Ruby 3.1 onwards with a new TracePoint method mentioned in [this debug.rb PR](https://github.com/ruby/debug/pull/558). I'm running Ruby 2.7.7 so I tried Break instead, which worked!
I was hoping to get this mentioned in the README since it wasn't very clear to me what the problem was with debug.rb until I spent a bit of time trawling through a couple of GH issues.

Clarify debug.rb compatibility in README

---

README.md

These are just some small language/grammar tweaks that tripped me up while reading through the `README`.

Fix small typo & clarify some grammar in the docs

---

.github/workflows/ci.yml
.github/workflows/keep-an-eye-on-ruby-head.yml

GitHub is [planning to upgrade to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Versions prior to actions/checkout v3 use an outdated version of node, so we will upgrade to actions/checkout v4, where [Node 20 is the default](https://github.com/actions/checkout/releases/tag/v4.0.0).

Bump actions/checkout

---

lib/zeitwerk/explicit_namespace.rb

This is totally nitpicky, but it's easier to assume `Object.equal?` is pristine, while for a random user defined module, it could have been changed.

Prefer `Object.equal?` over unknown module `equal?` method

---

lib/zeitwerk/cref.rb
lib/zeitwerk/explicit_namespace.rb
lib/zeitwerk/loader.rb
test/lib/zeitwerk/test_autovivification.rb
test/lib/zeitwerk/test_unload.rb
test/lib/zeitwerk/test_unregister.rb

Explicit namespaces have an internal hash that maps the cpaths of known explicit namespaces to be loaded to the loader that manages them.
Every added constant needs to verify if there is a loader for the given pair (mod, cname), and that runs for all constants added, globally. So it is a hot spot worth of micro-optimizations.
In particular, for top-level constants (which are common and go through that callback during boot) nowadays we invoke `Symbol#name` and then perform a string lookup. Technically, we can save `Symbol#name` and have a symbol lookup instead, which is faster.
Registering performs an additional comparison now, but registering is more rare than const added.
The hypothesis would be that this may speed boot time up a little bit, and that eager loading would be more or less …

Micro-optimization for explicit namespaces

---

.github/workflows/ci.yml

Compare [before](https://github.com/fxn/zeitwerk/actions/runs/11299692884/usage) and [after](https://github.com/eregon/zeitwerk/actions/runs/11305055840/usage)

Speedup the CI on Windows by skipping the toolchain as it's not needed

---

.github/workflows/ci.yml
README.md
test/lib/zeitwerk/test_ruby_compatibility.rb

Now all tests pass, except https://github.com/oracle/truffleruby/issues/2431 for well-known reasons.
I would like to add TruffleRuby in CI so it's easy to notice any potential issue going forward.

Add TruffleRuby in CI

---

.github/workflows/ci.yml
.github/workflows/keep-an-eye-on-ruby-head.yml

After addressing https://github.com/oracle/truffleruby/issues/3683, we can start testing against `truffleruby`, and keep an eye on `truffleruby-head` too.

Add TruffleRuby stable to CI

---

lib/zeitwerk/loader.rb
zeitwerk.gemspec

Reflects default branch changes from master to main where appropriate. Silences the "Branch master was renamed to main." banner on GitHub. Skips occurrences in CHANGELOG.md to avoid altering past entries.

Update links from master to main
